const covid19ImpactEstimator = (e) => {
  const {
    region: t, reportedCases: o, periodType: n, timeToElapse: a, totalHospitalBeds: c
  } = e; const r = 10 * o; const s = { currentlyInfected: r }; const l = 50 * o; const i = { currentlyInfected: l }; let u; const d = ((e, t) => { let o = 2 ** Math.floor(t / 3); return u = t, e === 'weeks' ? (u = 7 * t, o = 2 ** Math.floor(7 * t / 3)) : e === 'months' && (u = 30 * t, o = Math.floor(2 ** (30 * t / 3))), o; })(n, a); const m = r * d; s.infectionsByRequestedTime = m; const y = l * d; i.infectionsByRequestedTime = y; let p = 0.15 * s.infectionsByRequestedTime; p = p < 0 ? Math.ceil(p) : Math.floor(p), s.severeCasesByRequestedTime = p; let q = 0.15 * i.infectionsByRequestedTime; q = q < 0 ? Math.ceil(q) : Math.floor(q), i.severeCasesByRequestedTime = q; let v = 0.35 * c - s.severeCasesByRequestedTime; v = v < 0 ? Math.ceil(v) : Math.floor(v), s.hospitalBedsByRequestedTime = v; let S = 0.35 * c - i.severeCasesByRequestedTime; S = S < 0 ? Math.ceil(S) : Math.floor(S), i.hospitalBedsByRequestedTime = S, s.casesForICUByRequestedTime = Math.floor(0.05 * s.infectionsByRequestedTime), i.casesForICUByRequestedTime = Math.floor(0.05 * i.infectionsByRequestedTime), s.casesForVentilatorsByRequestedTime = Math.floor(0.02 * s.infectionsByRequestedTime), i.casesForVentilatorsByRequestedTime = Math.floor(0.02 * i.infectionsByRequestedTime); const g = Math.floor(s.infectionsByRequestedTime * t.avgDailyIncomePopulation * t.avgDailyIncomeInUSD / u); s.dollarsInFlight = g; const I = Math.floor(i.infectionsByRequestedTime * t.avgDailyIncomePopulation * t.avgDailyIncomeInUSD / u); return i.dollarsInFlight = I, { data: e, impact: s, severeImpact: i };
}; const toggleForms = () => { document.querySelector('.region-data').setAttribute('style', 'opacity: 0; z-index: -50'), document.querySelector('.cases-data').setAttribute('style', 'opacity: 1; z-index: 50'), document.querySelector(':root').style.setProperty('--currentColor', '#007bff'); }; document.querySelector('.step-but').onclick = (() => {
  const e = {
    name: document.querySelector('select[data-name]'), avgAge: document.querySelector('input[data-avgAge]'), avgDailyIncomeInUSD: document.querySelector('input[data-avgDailyIncomeInUSD]'), avgDailyIncomePopulation: document.querySelector('input[data-avgDailyIncomePopulation]')
  }; if (e.name.value && e.avgAge.value && e.avgDailyIncomeInUSD.value && e.avgDailyIncomePopulation.value) { document.querySelector('#name').dataset.name = e.name.value, e.avgDailyIncomeInUSD.dataset.avgDailyIncomeInUSD = e.avgDailyIncomeInUSD.value; const t = e.avgDailyIncomePopulation.value; return e.avgDailyIncomePopulation.dataset.avgDailyIncomePopulation = t, e.avgAge.dataset.avgAge = e.avgAge.value, document.querySelector('.region-data').setAttribute('style', 'opacity: 0; z-index: -50'), document.querySelector('.cases-data').setAttribute('style', 'opacity: 1; z-index: 50'), void document.querySelector(':root').style.setProperty('--currentColor', '#007bff'); } const t = document.querySelector('aside h4'); return t.textContent = 'Please fill all fields.', t.style.color = 'red', '';
}); const runEstimator = (e) => {
  const t = covid19ImpactEstimator(e); const { data: o, impact: n, severeImpact: a } = t; const {
    region: c, periodType: r, timeToElapse: s, reportedCases: l, population: i, totalHospitalBeds: u
  } = o; const {
    currentlyInfected: d, infectionsByRequestedtime: m, severeCasesByRequestedTime: y, hospitalBedsByRequestedTime: p, casesForICUByRequestedTime: q, casesForVentilatorsByRequestedTime: v, dollarsInFlight: S
  } = n; const {
    currentlyInfected: g, infectionsByRequestedtime: I, severeCasesByRequestedTime: B, hospitalBedsByRequestedTime: f, casesForICUByRequestedTime: C, casesForVentilatorsByRequestedTime: T, dollarsInFlight: D
  } = a; const {
    name: R, avgAge: h, avgDailyIncomeInUSD: x, avgDailyIncomePopulation: F
  } = c; document.querySelector('.reg').textContent = R, document.querySelector('.avgAge').textContent = h, document.querySelector('.avgDailyIncomeInUSD').textContent = x, document.querySelector('.avgDailyIncomePopulation').textContent = F, document.querySelector('.periodType').textContent = r, document.querySelector('.timeToElapse').textContent = s, document.querySelector('.reportedCases').textContent = l, document.querySelector('.population').textContent = i, document.querySelector('.totalHospitalBeds').textContent = u, document.querySelector('.impact-cont .currentlyInfected').textContent = d, document.querySelector('.impact-cont .infectionsByRequestedtime').textContent = m, document.querySelector('.impact-cont .severeCasesByRequestedTime').textContent = y, document.querySelector('.impact-cont .hospitalBedsByRequestedTime').textContent = p, document.querySelector('.impact-cont .casesForICUByRequestedTime').textContent = q, document.querySelector('.impact-cont .casesForVentilatorsByRequestedTime').textContent = v, document.querySelector('.impact-cont .dollarsInFlight').textContent = S, document.querySelector('.severe-impact-cont .currentlyInfected').textContent = g, document.querySelector('.severe-impact-cont .infectionsByRequestedtime').textContent = I, document.querySelector('.severe-impact-cont .severeCasesByRequestedTime').textContent = B, document.querySelector('.severe-impact-cont .hospitalBedsByRequestedTime').textContent = f, document.querySelector('.severe-impact-cont .casesForICUByRequestedTime').textContent = C, document.querySelector('.severe-impact-cont .casesForVentilatorsByRequestedTime').textContent = T, document.querySelector('.severe-impact-cont .dollarsInFlight').textContent = D, document.querySelector('.form-container section').style.width = '100%', document.querySelector('aside').style.width = '100%', document.querySelector('.steps-shift').style.display = 'none', document.querySelector('form').style.display = 'none', document.querySelector('aside h1').style.display = 'none', document.querySelector('aside h4').style.display = 'none', document.querySelector('.results').style.display = 'initial', document.querySelector('.data-main-cont').style.display = 'initial';
}; document.querySelector('form').onsubmit = ((e) => {
  e.preventDefault(); const t = {
    region: {
      name: document.querySelector('select[data-name]').dataset.name, avgAge: document.querySelector('input[data-avgAge]').dataset.avgAge, avgDailyIncomeInUSD: document.querySelector('input[data-avgDailyIncomeInUSD]').dataset.avgDailyIncomeInUSD, avgDailyIncomePopulation: document.querySelector('input[data-avgDailyIncomePopulation]').dataset.avgDailyIncomePopulation
    },
    periodType: document.querySelector('select[data-name]').value,
    timeToElapse: document.querySelector('input[data-time-to-elapse]').value,
    reportedCases: document.querySelector('input[data-reported-cases]').value,
    population: document.querySelector('input[data-population]').value,
    totalHospitalBeds: document.querySelector('input[data-total-hospital-beds]').value
  }; runEstimator(t);
}), document.querySelector('.reload').onclick = (() => { window.location.reload(); });
